;[
	{
		AdvancedJavascript: {
			Foundations: {
				JavascriptEngine,
				JavascriptRuntime,
				Interpreter_Compiler_JITCompiler,
				WritingOptimizedCode,
				CallStack_MemoryHeap,
				StackOverflow_MemoryLeaks,
				GarbageCollection,
				Nodejs,
				SingleThreadedModel,
				Execution_Context,
				LexicalEnvironment,
				ScopeChain,
				Hoisting,
				FunctionInvocation,
				FunctionScopeVsBlockScope,
				DynamicVsLexicalScope,
				this_callApplyBind,
				IIFE,
			},
			TypesInJavascript: {
				StaticVsDynamicallyTyped,
				PrimitiveTypes,
				PassByReferenceVsPassByValue,
				TypeCoercion,
				ArraysFunctionsObjects,
			},
			TheTwoPillars: {
				One_Closures,
				Two_PrototypalInheritance,
				HigherOrderFunctions,
				FunctionsVsObjects,
				Scheme_Java,
			},
			OOPvsFP: {
				ObjectOrientedProgramming: [
					'thisKeyword',
					'newKeyword',
					'Prototype',
					'ES6Classes',
					'Java',
					'Inheritance',
					'Object.create()',
					'PrivateVsPublic',
					'FourPrinciplesOfOOP',
				],
				CompositionVsInheritance,
				FunctionalProgramming: [
					'Curry',
					'PartialApplication',
					'PureFunctions',
					'ReferentialTransparency',
					'Compose',
					'Pipe',
				],
			},
			Extras: {
				AsynchronousJavascript: [
					'WebAPIs',
					'Async_Await',
					'Callbacks',
					'MicrotaskQueue(JobQueue)',
					'TaskQueue(CallbackQueue)',
					'Promises',
					'EventLoop',
				],
				ErrorHandling,
				ModulesInJavascript: [
					'NativeESModules',
					'CommonJS',
					'UMD',
					'AMD',
					'IIFE',
				],
			},
		},
	},
]
