;[
	{
		Javascript: {
			Basis: {
				Javascript_Engine,
				Javascript_Runtime,
				Interpreter_Compiler_JITCompiler,
				Writing_Optimized_Code,
				CallStack_MemoryHeap,
				StackOverflow_MemoryLeaks,
				Garbage_Collection,
				Nodejs,
				Single_Threaded_Model,
				Execution_Context,
				Lexical_Environment,
				Scope_Chain,
				Hoisting,
				Function_Invocation,
				Function_Scope_Vs_Block_Scope,
				Dynamic_Vs_Lexical_Scope,
				this_CallApplyBind,
				IIFE,
			},
			DataTypes: {
				Static_Vs_Dynamically_Typed,
				Primitive_Types,
				Pass_By_Reference_Vs_Pass_By_Value,
				Type_Coercion,
				Arrays_Functions_Objects,
			},
			TheTwoLegs: {
				Closures,
				Prototypal_Inheritance,
				Higher_Order_Functions,
				Functions_Vs_Objects,
				Scheme_Java,
			},
			OOP_FP: {
				ObjectOrientedProgramming: [
					'thisKeyword',
					'newKeyword',
					'Prototype',
					'ES6Classes',
					'Java',
					'Inheritance',
					'Object.create()',
					'PrivateVsPublic',
					'FourPrinciplesOfOOP',
				],
				Composition_Vs_Inheritance,
				Functional_Programming: [
					'Curry',
					'PartialApplication',
					'PureFunctions',
					'ReferentialTransparency',
					'Compose',
					'Pipe',
				],
			},
			Extras: {
				Asynchronous_Javascript: [
					'Web_APIs',
					'Async_Await',
					'Callbacks',
					'Microtask_Queue(JobQueue)',
					'Task_Queue(CallbackQueue)',
					'Promises',
					'EventLoop',
				],
				Error_Handling,
				Modules_In_Javascript: [
					'NativeESModules',
					'CommonJS',
					'UMD',
					'AMD',
					'IIFE',
				],
			},
		},
	},
]
